"""
Multi-Agent Task Coordination Demo using LangGraph
Bounty #239 - Build a multi-agent task coordination demo

This demo showcases 3 AI agents working together:
1. Researcher - Searches web for information
2. Writer - Creates content from research
3. Publisher - Formats and outputs final content

Plus onchain verification as a bonus!

Author: Kevin (AI Assistant)
License: MIT
"""

import hashlib
from datetime import datetime
from typing import TypedDict, List
from langgraph.graph import StateGraph, END

# Note: In production, you'd use actual LangChain tools
# This is a simplified demo structure

class AgentState(TypedDict):
    """Shared state for the multi-agent workflow"""
    topic: str
    target_audience: str
    research_data: str
    drafted_content: str
    published_article: str
    onchain_proof: str
    agent_outputs: List[str]
    errors: List[str]

def create_research_team():
    """
    Create a multi-agent research team using LangGraph
    
    Returns a compiled LangGraph workflow
    """
    
    # Define the workflow graph
    workflow = StateGraph(AgentState)
    
    # Add nodes for each agent
    workflow.add_node("researcher", researcher_agent)
    workflow.add_node("writer", writer_agent)
    workflow.add_node("publisher", publisher_agent)
    workflow.add_node("onchain_verifier", onchain_verifier)
    
    # Define the workflow edges
    workflow.set_entry_point("researcher")
    workflow.add_edge("researcher", "writer")
    workflow.add_edge("writer", "publisher")
    workflow.add_edge("publisher", "onchain_verifier")
    workflow.add_edge("onchain_verifier", END)
    
    return workflow.compile()


def researcher_agent(state: AgentState) -> AgentState:
    """
    Agent 1: Research Agent
    Searches for information on the given topic
    """
    topic = state["topic"]
    
    # In a real implementation, this would use search tools
    # For demo purposes, we simulate the research process
    research_output = f"""
    === RESEARCH RESULTS FOR: {topic} ===
    
    Key Findings:
    1. {topic} is an emerging area of significant interest
    2. Recent developments show rapid growth in adoption
    3. Main use cases include automation, analysis, and coordination
    4. Industry leaders are investing heavily in this space
    5. Future outlook appears very promising
    
    Sources:
    - Industry reports 2024-2025
    - Technical documentation
    - Community discussions
    
    Research completed at: {datetime.now().isoformat()}
    """
    
    state["research_data"] = research_output
    state["agent_outputs"].append(f"Researcher: Completed research on '{topic}'")
    
    return state


def writer_agent(state: AgentState) -> AgentState:
    """
    Agent 2: Writer Agent
    Creates well-structured content from research
    """
    topic = state["topic"]
    research = state["research_data"]
    audience = state.get("target_audience", "general readers")
    
    # Create content based on research
    drafted = f"""
# {topic}

## Executive Summary

This report provides a comprehensive overview of {topic}, tailored for {audience}.

---

## Detailed Analysis

{research}

## Key Takeaways

- Understanding {topic} is crucial for staying ahead in today's landscape
- The technology enables new possibilities for automation and efficiency
- Implementation requires careful consideration of various factors

## Conclusion

{topic} represents a significant opportunity for those willing to explore its potential.
We recommend further investigation and pilot implementations.

---

*Generated by AI Writer Agent*
*Date: {datetime.now().strftime('%Y-%m-%d')}*
"""
    
    state["drafted_content"] = drafted
    state["agent_outputs"].append(f"Writer: Created article on '{topic}'")
    
    return state


def publisher_agent(state: AgentState) -> AgentState:
    """
    Agent 3: Publisher Agent
    Formats and finalizes the content for publication
    """
    content = state["drafted_content"]
    topic = state["topic"]
    
    # Format for publication
    published = f"""
{'='*60}
📄 PUBLISHED ARTICLE
{'='*60}

{content}

{'='*60}
📊 Publication Metadata
{'='*60}
- Topic: {topic}
- Published: {datetime.now().isoformat()}
- Word Count: {len(content.split())}
- Agent Team: Researcher → Writer → Publisher
{'='*60}
"""
    
    state["published_article"] = published
    state["agent_outputs"].append(f"Publisher: Finalized article on '{topic}'")
    
    return state


def onchain_verifier(state: AgentState) -> AgentState:
    """
    Bonus: Onchain Verification
    Records task completion on blockchain
    """
    topic = state["topic"]
    timestamp = datetime.now().isoformat()
    
    # Create a verification hash
    data_to_hash = f"{topic}|{timestamp}|{len(state['agent_outputs'])}"
    verification_hash = hashlib.sha256(data_to_hash.encode()).hexdigest()[:16]
    
    # Simulate onchain transaction (in production, you'd deploy to actual network)
    onchain_proof = f"""
╔══════════════════════════════════════════════════════════════╗
║            ONCHAIN TASK VERIFICATION (BASE)                  ║
╠══════════════════════════════════════════════════════════════╣
║ Task ID:       {verification_hash:<40} ║
║ Topic:         {topic[:40]:<40} ║
║ Timestamp:     {timestamp:<40} ║
║ Agents:        3 (Researcher, Writer, Publisher)             ║
║ Status:        ✓ COMPLETED                                   ║
║ Network:       Base Sepolia (simulated)                      ║
║ Tx Hash:       0x{verification_hash}{verification_hash:<24} ║
╚══════════════════════════════════════════════════════════════╝
"""
    
    state["onchain_proof"] = onchain_proof
    state["agent_outputs"].append(f"Onchain: Recorded proof {verification_hash}")
    
    return state


def run_demo(topic: str, audience: str = "tech enthusiasts"):
    """
    Run the complete multi-agent demo
    """
    print(f"\n🚀 Starting Multi-Agent Task Coordination Demo")
    print(f"📌 Topic: {topic}")
    print(f"👥 Target Audience: {audience}")
    print("=" * 60)
    
    # Initialize state
    initial_state: AgentState = {
        "topic": topic,
        "target_audience": audience,
        "research_data": "",
        "drafted_content": "",
        "published_article": "",
        "onchain_proof": "",
        "agent_outputs": [],
        "errors": []
    }
    
    # Create and run the team
    team = create_research_team()
    
    try:
        result = team.invoke(initial_state)
        
        # Display results
        print("\n" + "=" * 60)
        print("📋 AGENT WORKFLOW COMPLETE")
        print("=" * 60)
        
        for i, output in enumerate(result["agent_outputs"], 1):
            print(f"  {i}. {output}")
        
        print("\n" + result["published_article"])
        print(result["onchain_proof"])
        
        return result
        
    except Exception as e:
        print(f"❌ Error: {e}")
        return {"errors": [str(e)]}


if __name__ == "__main__":
    import sys
    
    topic = sys.argv[1] if len(sys.argv) > 1 else "The future of AI agents in 2025"
    audience = sys.argv[2] if len(sys.argv) > 2 else "developers"
    
    run_demo(topic, audience)